AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service


Resources:
  DakobedSnotelApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
      BinaryMediaTypes:
        - application/audio

  SnotelQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SnotelQueryFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Snotel
      CodeUri: snotel/
      Handler: snotel_lambda.lambda_handler
      Runtime: python3.7
      Events:
        SnotelApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedSnotelApi
            Path: /snotel
            Method: GET
