AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Resources:
  DakobedSnotelApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-apis/ebbef0f09c111c3718fc62265b7c3ea4
  SnotelQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SnotelQueryFunction
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Snotel
      CodeUri: s3://dakobed-serverless-apis/1f275c59b555985c7d7c2ef34032bd65
      Handler: snotel_lambda.lambda_handler
      Runtime: python3.7
      Events:
        SnotelApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedSnotelApi
            Path: /snotel
            Method: GET
